microsoft/dotnet-framework-docker

4.7/Dockerfile, README.md
- In support of https://github.com/dotnet/designs/issues/7
- Builds on top of #17.
- Tried to convert the Dockerfiles to PowerShell. Was unable to after spending non-zero time futzing with it. Couldn't figure out how to do the combination of: run the setup, pass arguments to the setup and wait on the setup until deleting it. That all worked w/o issue in cmd.exe.
=> Add support for .NET Framework 4.7

README.md
Looks like the readme wasn't updated when the 1770 images were published.
=> Update readme for 10.0.14393.1770 release

README.md
Adopting a stable name for Windows Server 2016 images: `ltsc2016`
=> Update base image names

4.7.1-windowsservercore-1709/build/Dockerfile, 4.7.1-windowsservercore-ltsc2016/build/Dockerfile
Fixes #49 
I made a slash style change because I noticed the '/' wasn't getting inverted when setting the PATH.  I thought it was best to use std Windows '\' just in case something was reading the PATH and didn't handle '/'.
The SDK adds 360MB to the image.
=> Add .NET Core SDK to Build images

3.5-windowsservercore-1709/runtime/Dockerfile, 3.5-windowsservercore-ltsc2016/runtime/Dockerfile
These changes address the following:
1.  Remove the unnecessary installer files that are currently included in the 3.5 runtime docker images.  These files are significant in size (464MB for 1709 and 1.32 GB for ltsc2016)
1.  Contents of the 3.5 Dockerfiles are transparent to users.  The LCU being installed in the Dockerfile was not reflective of what was contained in the image.
1.  Dockerfile is now buildable by anyone.  This will allow users to create their own 3.5 image in the case they can't use these 3.5 images.
Fixes #58 
Fixes #45
=> Refactor 3.5 runtime Dockerfiles

build-pipeline/dotnet-framework-docker-post-image-build.json, build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json, build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json
1. Increase build timeouts.  When new base os images have to be pulled and the network is slow, the builds would timeout periodically.
2. Modified cleanup logic to preserve base os images.
=> build tweaks to prevent timeouts and preserve base os images.

build-and-test.ps1, build-pipeline/dotnet-framework-docker-post-image-build.json, build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json, build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json, build-pipeline/pipeline.json, manifest.json, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs, tests/run-tests.ps1
This allows the repo to easily get built and pushed to an Azure Container Registry which is needed at times for testing purposes.
=> Remove hard coded repo owner from tests

build-pipeline/dotnet-framework-docker-post-image-build.json, build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json, build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json, build-pipeline/pipeline.json
Update official builds to use `build-and-test.ps1`.  Thus, CI and official builds use the same pattern to build and test images.
Fixes https://github.com/Microsoft/dotnet-framework-docker/issues/82
=> Use build-and-test script in official builds

manifest.samples.json, samples/README.md, samples/wcfapp/Dockerfile.client, samples/wcfapp/Dockerfile.console, samples/wcfapp/Dockerfile.web, samples/wcfapp/README.md, samples/wcfapp/WcfClient/App.config, samples/wcfapp/WcfClient/IService1.cs, samples/wcfapp/WcfClient/Program.cs, samples/wcfapp/WcfClient/Properties/AssemblyInfo.cs, samples/wcfapp/WcfClient/WcfClient.csproj, samples/wcfapp/WcfServiceConsoleApp/App.config, samples/wcfapp/WcfServiceConsoleApp/Dockerfile, samples/wcfapp/WcfServiceConsoleApp/IService1.cs, samples/wcfapp/WcfServiceConsoleApp/Program.cs, samples/wcfapp/WcfServiceConsoleApp/Properties/AssemblyInfo.cs, samples/wcfapp/WcfServiceConsoleApp/Service1.cs, samples/wcfapp/WcfServiceConsoleApp/WcfServiceConsoleApp.csproj, samples/wcfapp/WcfServiceWebApp/Dockerfile, samples/wcfapp/WcfServiceWebApp/IService1.cs, samples/wcfapp/WcfServiceWebApp/Properties/AssemblyInfo.cs, samples/wcfapp/WcfServiceWebApp/Service1.svc, samples/wcfapp/WcfServiceWebApp/Service1.svc.cs, samples/wcfapp/WcfServiceWebApp/WcfServiceWebApp.csproj, samples/wcfapp/WcfServiceWebApp/Web.Debug.config, samples/wcfapp/WcfServiceWebApp/Web.Release.config, samples/wcfapp/WcfServiceWebApp/Web.config, samples/wcfapp/docker-compose-iishosted.yml, samples/wcfapp/docker-compose-selfhosted.yml, samples/wcfapp/wcfapp.sln
#129 
I just copied the WCF sample from old repo to here. Please let me know if there are any new formats we need to follow. Thanks!
@MichaelSimons @richlander @Lxiamail
=> Add WCF sample

.vsts-pipelines/builds/microsoft-dotnet-framework.yml, .vsts-pipelines/phases/build-all.yml, .vsts-pipelines/phases/build-amd64.yml, .vsts-pipelines/phases/copy-images.yml, .vsts-pipelines/phases/publish-finalize.yml, .vsts-pipelines/phases/test-amd64.yml, .vsts-pipelines/steps/docker-init-linux.yml, .vsts-pipelines/steps/docker-init-windows.yml, scripts/Invoke-PullImage.ps1, scripts/pull-image.sh
- Use latest image builder with fix for dotnet/docker-tools#105
- Add retry logic when pulling Docker images
- Refactor startingPhase into singlePhase. This provides more robust control such as being able to only perform a build.
- Encapsulate image-builder retrieval/setup within single yml - docker-init-windows.yml
- Fix issue with build path not getting set correctly between samples and product builds.
@dotnet-bot dotnet-bot Linked skip ci please
=> Misc changes to build definitions related to cleanup and stabilization

.vsts-pipelines/phases/build-all.yml, .vsts-pipelines/phases/build-amd64.yml, .vsts-pipelines/phases/copy-images.yml, .vsts-pipelines/steps/docker-init-windows.yml
- Some recent build changes broke the samples build.  The samples build the same Dockerfiles on multiple platforms therefore there needs to be an os-version filter specified in order to select the correct entry within the manifest.
- Fixed an `if` condition to use the correct syntax.
=> Fixup samples build

tests/run-tests.ps1
- Fixed an issue with CI in that the tests are not running with the images built by CI.  
- Update the version of .NET Core used by the tests to 2.1 since 2.0 is EOL.
=> Fix CI to run with local images

README.md, samples/README.DockerHub.md, scripts/Get-TagsDocumentation.ps1, scripts/ReadmeTagsDocumentationTemplate.md, scripts/SamplesReadmeTagsDocumentationTemplate.md
This new format is what is used in the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) repo.
I also modified the infrastructure used to generate the tags section of the readme from the manifest.  Currently after the readme is generated it requires a few minor hand edits to get it in the desired format.  These changes eliminate that.
=> Update Dockerfile link pattern used in readme tags section

.vsts-pipelines/phases/build-amd64.yml, README.dotnet-framework-build.md, manifest.json, netci.groovy, samples/aspnetapp/README.md, samples/aspnetmvcapp/README.md, samples/dotnetapp/README.md, samples/wcfapp/README.md
This is in preparation for deleting the repo which was announced in https://github.com/Microsoft/dotnet-framework-docker/issues/125
Fixes https://github.com/Microsoft/dotnet-framework-docker/issues/201
=> Remove references to the microsoft/dotnet-framework-build repo

.vsts-pipelines/jobs/build-test-publish-repo.yml, .vsts-pipelines/steps/generate-matrix.yml, .vsts-pipelines/variables/docker-images.yml
Reference the newest version of ImageBuilder which has renamed the matrix types when generating a matrix. As part of these changes, I've factored out the identifiers for those matrix types into parameters such that they map to the particular jobs that are being execute (i.e. build, test, publish). The matrix values are then referenced dynamically by referencing the appropriate parameter. This was done in order to better position things for better support for the PR build refactoring that will require the ability to dynamically select which matrix type will be used for the build jobs.
=> Reference new image builder

README.runtime.md, README.samples.md, README.sdk.md, scripts/Get-TagsDocumentation.ps1
This was a regression introduced during the move to MCR.
@dotnet-bot skip ci please.
=> Fix broken Dockerfile links in readmes

3.5/runtime/windowsservercore-1803/Dockerfile, 3.5/runtime/windowsservercore-ltsc2016/Dockerfile, 3.5/runtime/windowsservercore-ltsc2019/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile, 4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile, 4.7/runtime/windowsservercore-ltsc2016/Dockerfile
.NET Fx leaves files in the TEMP folder after running the installer.  These should be cleaned up.
Fixes #255
=> Delete temp folder after installing .NET Fx

3.5/sdk/windowsservercore-1803/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.7.1/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-1803/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile
It was originally thought that the VS packages folder could be deleted from the image to provide some savings on image size.  But that folder is actually needed in order to execute any VS installer commands.  For example, modifying the existing installation with an additional component.  Without the VS packages folder, the installer will not recognize VS as already being installed.  So we should revert the change to remove this folder.
=> Ensure that VS packages folder is not deleted as part of cleanup

README.md, samples/aspnetapp/Dockerfile, samples/aspnetapp/Dockerfile.windowsservercore-ltsc2016, samples/aspnetapp/README.md, samples/aspnetapp/aspnetapp/Web.config, samples/aspnetapp/aspnetapp/aspnetapp.csproj, samples/aspnetmvcapp/Dockerfile, samples/aspnetmvcapp/aspnetmvcapp/Web.config, samples/aspnetmvcapp/aspnetmvcapp/aspnetmvcapp.csproj, samples/dotnetapp/Dockerfile, samples/dotnetapp/Dockerfile.basic, samples/dotnetapp/README.md, samples/dotnetapp/dotnetapp/dotnetapp.csproj, samples/dotnetapp/tests/tests.csproj, samples/wcfapp/Dockerfile.client, samples/wcfapp/Dockerfile.console, samples/wcfapp/Dockerfile.web, samples/wcfapp/README.md, samples/wcfapp/WcfClient/App.config, samples/wcfapp/WcfClient/WcfClient.csproj, samples/wcfapp/WcfServiceConsoleApp/App.config, samples/wcfapp/WcfServiceConsoleApp/WcfServiceConsoleApp.csproj, samples/wcfapp/WcfServiceWebApp/WcfServiceWebApp.csproj, samples/wcfapp/WcfServiceWebApp/Web.config
Updates the samples and readmes to reference .NET Framework 4.8 instead of 4.7.2.
=> Update samples to use 4.8

.vsts-pipelines/jobs/build-test-publish-repo.yml, .vsts-pipelines/variables/common.yml
Ensure that the Component Detection task is only executed once for the entire build. Currently it gets run in every job which is not necessary. These changes explicitly add it to one job and sets a variable to ensure it is not automatically added to other jobs.
=> Explicitly add component governance task

.vsts-pipelines/jobs/build-images.yml, .vsts-pipelines/steps/test-images-windows-client.yml, manifest.json, scripts/Invoke-CleanupDocker.ps1, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs
The PR build is having issues completing in a reasonable amount of time.  I've trimmed the test matrix a bit to cut down on the number of images that need to be built in a given leg but still provide decent enough coverage of runtime/sdk combos on the whole.
I also found that there was an issue in the definition of the versionFilter parameter for tests that was causing the 4.7 leg to attempt to run tests for 4.7.1 and 4.7.2.  This is due to the '*' character that was appended to the 4.7 string causing it to match those other versions.  I've removed it so that it will only match on the exact version string.
=> Fix PR build runs

.vsts-pipelines/stages/build-test-publish-repo.yml
During build stage of the pipeline, the pipeline cannot be cancelled. Things will keep right on running until all the jobs in the stage have finished. This is due to a succeeded() check missing in the condition of the build stage. Adding this to the condition fixes the issue.
=> Allow builds to be cancelled

3.5/runtime/windowsservercore-1803/Dockerfile, 3.5/runtime/windowsservercore-1903/Dockerfile, 3.5/runtime/windowsservercore-ltsc2016/Dockerfile, 3.5/runtime/windowsservercore-ltsc2019/Dockerfile, 3.5/sdk/windowsservercore-1803/Dockerfile, 3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.6.2/runtime/windowsservercore-ltsc2016/Dockerfile, 4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile, 4.7.1/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-1803/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile, 4.7/runtime/windowsservercore-ltsc2016/Dockerfile, 4.8/runtime/windowsservercore-1803/Dockerfile, 4.8/runtime/windowsservercore-ltsc2016/Dockerfile, 4.8/runtime/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1803/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-ltsc2016/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile
Refactors all of the Dockerfiles to address several issues:
* Removes switching between shells.  The default CMD shell is now used throughout the Dockerfile and only switches the shell to be PowerShell at the very end of the Dockerfile.  In certain cases PowerShell commands are required for certain operations but those are done by explicitly calling the PowerShell exe in the CMD shell.
* Fixes inconsistencies for certain actions.  Example: #232 
* Ensure failed commands are not hidden by using '&&' instead of '&' when batching together multiple commands.
* Overall cleanup of formatting.
Related to #251 
Related to #232 
Related to #202 
Related to #43
=> Dockerfile refactoring

eng/pipelines/dotnet-framework.yml
The pipeline fails when running in the public project because it ends up with duplicate `windowsAmdBuildJobTimeout` parameters being defined.
=> Fix pipeline timeouts

3.5/sdk/windowsservercore-1803/Dockerfile, 3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1803/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile
When extracting the sdk_tools48.zip file, both a .cab and .msi file are placed in the directory but only the .msi file is being cleaned up.  These changes ensure that everything is properly cleaned up.
Fixes #297
=> Clean up sdk_tools48.cab file

4.7.2/runtime/windowsservercore-1803/Dockerfile, 4.7.2/runtime/windowsservercore-ltsc2019/Dockerfile, 4.8/runtime/windowsservercore-1903/Dockerfile
The Windows base images do not have ngen images included in them which leads to poor performance.  Most of our images are installing .NET on top of the Windows base image and we are ngen-ing as part of that.  But there are a few remaining which do not since they have the required version of .NET Framework already installed in the base image.  For those, we need to ensure that we run ngen.
Fixes #211
=> Ensure runtime images are ngen'd

eng/common/templates/jobs/test-images-windows-client.yml, eng/common/templates/steps/test-images-linux-client.yml, eng/common/templates/steps/test-images-windows-client.yml, eng/pipelines/dotnet-framework-wcf.yml, eng/pipelines/dotnet-framework.yml, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs, tests/run-tests.ps1
This PR deals with adding support for the infrastructure to know if the current build is for WCF or Runtime and then only running tests that apply.
We are using the "dotnet test" filtering expression to select which tests to run.
https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests#xunit
I've verified that these changes will correctly differentiate between 'WCF' and 'Runtime' and run the correct tests in ImageTests.cs
https://dev.azure.com/dnceng/internal/_build/results?buildId=271563
I was not able to test the change made to `steps/test-images-linux-client.yml` because I'm not sure how to trigger the Linux build path when kicking off the build def.
=> Stebon/hongli wcf/wcfchanges

README.wcf.md, eng/Get-TagsDocumentation.ps1, eng/pipelines/variables/common.yml
1. The readme links on DH are currently broken as they reference `https://github.com/dotnet/dotnet-framework-docker/` instead of `https://github.com/dotnet/dotnet-framework-docker/`.  This was a regression the came in with the common eng infra.
1. Add WCF support to the Get-TagsDocumentation.ps1
1. Fix the incorrect Dockerfile links in the WCF readme
=> Fix broken Dockerfile links in the readmes

eng/common/Invoke-CleanupDocker.ps1, eng/common/templates/jobs/build-images.yml, eng/common/templates/jobs/post-build.yml, eng/common/templates/jobs/publish.yml, eng/common/templates/stages/build-test-publish-repo.yml, eng/common/templates/steps/cleanup-docker-linux.yml, eng/common/templates/steps/download-build-artifact.yml, eng/common/templates/steps/init-docker-linux.yml, eng/common/templates/steps/init-docker-windows.yml, eng/common/templates/steps/test-images-linux-client.yml, eng/common/templates/steps/test-images-windows-client.yml, eng/common/templates/variables/common.yml, eng/common/templates/variables/docker-images.yml, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs, tests/run-tests.ps1
Integrates the latest changes in the eng/common folder.
Since the logic in eng/common folder is now passing the ImageInfoPath argument to the run-tests PowerShell script, I've updated the script and test code to honor that argument and to pull images from the appropriate location (staging or MCR) based on whether the image tag is contained in the image info file.
=> Integrate eng/common folder

manifest.json, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeImageDescriptor.cs
Trims down the test matrix so that we don't have so much testing overhead but still maintain decent coverage.
Adds an additional test which verifies the expected targeting packs are installed on the SDK images.
Fixes #404
=> Trim test matrix

3.5/sdk/windowsservercore-1803/Dockerfile, 3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.7.1/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-1803/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile, 4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1803/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-ltsc2016/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile, README.sdk.md, manifest.json
* Updates the SDK images to the VS 16.3 versions of the Test Agent and Build Tools
* VS 16.3 now includes 4.8 so the 3.5 and 4.8 SDK images are updated to install 4.8 from Build Tools instead of from the blob storage install.
Fixes #276, #313, #323, #327
=> VS 16.3 updates

3.5/runtime/windowsservercore-1803/Dockerfile, 3.5/runtime/windowsservercore-1903/Dockerfile, 3.5/runtime/windowsservercore-ltsc2019/Dockerfile, 4.6.2/runtime/windowsservercore-ltsc2016/Dockerfile, 4.8/runtime/windowsservercore-1903/Dockerfile
The runtime Dockerfiles were not all following a consistent pattern around the ngen section.
1. The various Dockerfiles did not all of a comment around this section.
1. Some sections had a space between the ENV and RUN instructions.
1. The some but not all 3.5 Dockerfiles used `3.5` in the comment.
=> Modify runtime ngen Dockerfile comments to be consistent

3.5/sdk/windowsservercore-1803/Dockerfile, 3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1803/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-ltsc2016/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile
Adds commands to validate the installation of `vs_TestAgent.exe` and `vs_BuildTools.exe`.  Non-fatal errors in the installation do not cause a non-zero exit code to be returned for those two installers.  Rather, error information is written to a `dd_setup_*_errors.log` file in the `%TEMP%` folder. The validation checks whether any such file exists and throws an error with the content of that file if it exists.
Related to #419
=> Add install validation for TestAgent and BuildTools

3.5/runtime/windowsservercore-1909/Dockerfile, 3.5/sdk/windowsservercore-1909/Dockerfile, 4.8/runtime/windowsservercore-1909/Dockerfile, 4.8/sdk/windowsservercore-1909/Dockerfile, README.aspnet.md, README.runtime.md, README.sdk.md, README.wcf.md, manifest.json, tests/Microsoft.DotNet.Framework.Docker.Tests/EnvironmentVariableInfo.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
Fixes the incorrect syntax of environment variables in Dockerfiles for Windows 1909.  Adds unit tests to verify environment variables are set correctly for runtime and SDK images across all versions.
Fixes #452
=> Fix environment variable declarations in Dockerfiles for Windows 1909

.dockerignore
Having the `.git` folder listed in `.dockerignore` breaks build pipeline logic when we build an ImageBuilder image that wraps the repo contents.  By not including the `.git` folder, it prevents `git` commands from being used within the resulting container.
=> Remove .git folder from .dockerignore

tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SkippableTheoryAttribute.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs
Fixes #455 
Fixes #456 
This uncovered an [issue ](https://github.com/microsoft/dotnet-framework-docker/issues/474)with the ROSLYN_COMPILER_LOCATION variable being defined incorrectly.
=> Add ASP.NET and WCF environment variable tests

tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
Defines some unit tests which validate that the following tools can successfully execute in the SDK image:
* nuget.exe
* dotnet.exe
* vstest.console.exe
* gacutil.exe
This also implicitly validates these tools are available from the `PATH` environment variable.
Related: #86
=> Unit tests for tools installation in SDK images

tests/run-tests.ps1
We've got a new set of Windows Server 2016 build agents that appear to be configured with a minimum TLS version of 1.2.  This causes an error when attempting to download the .NET install script in the tests because the default protocol version of PowerShell is TLS 1.0.  Fixing this by explicitly setting the TLS version to 1.2 for that PowerShell script that does the download.  This is actually the prescribed way of doing this as documented here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script.
=> Set TLS protocol version to download .NET install script

build-and-test.ps1
Updates the `build-and-test.ps1` script to follow the same pattern used by https://github.com/dotnet/dotnet-docker/blob/master/build-and-test.ps1.  This defines `-BuildOnly` and `-TestOnly` parameters.  This is in preparation for the changes to remove testing logic from the common build script (https://github.com/dotnet/docker-tools/issues/364).
=> Refactor build script to follow dotnet-docker build script pattern

README.aspnet.md, README.md, README.runtime.md, README.samples.md, README.sdk.md, README.wcf.md
Added an 'Image Update Policy' section to the READMEs to call out when .NET Framework images will be updated. The purpose is to communicate our policy so that customers can know what to expect. The desired outcome is that more customers feel compelled to take a dependency on our images.
I also made a few other README edits to address MD rule violations.
=> Added 'Image Update Policy' section to the READMEs

eng/pipelines/dotnet-framework.yml
Ensures that PR builds will not trigger for commits that only consist of README or sample changes.
Fixes #495
=> Add path exclusions to pipeline

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md, .github/ISSUE_TEMPLATE/releases/vs-tools-release.md, eng/pipelines/dotnet-framework.yml
Defines two markdown files to be used as templates for creating issues for a release. These are stored in a `releases` subfolder since they are not intended to be available to select when creating a new issue.
Also includes a bug report issue template for the repo.
Related to dotnet/docker-tools#383
=> Add issue templates

.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md
The PT release issue template mistakenly included `mcr.microsoft.com/windows/servercore:1809` in the list of base images we're dependent on but we don't actually have a dependency on that tag.  Removing it.
=> Remove 1809 from list of base images to check

.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md
Now that there's a [script](https://github.com/dotnet/docker-tools/pull/411) to check the status of the base Windows images, the Patch Tuesday issue template can make use of it in the workflow.
=> Update PT issue template to check Windows images w/ script

build-and-test.ps1
Removing the `ExcludeArchitecture` parameter because it had been removed from the common build script in https://github.com/dotnet/docker-tools/pull/416.  It was replaced by the presence of the `ArchitectureFilter` parameter.
=> Remove ExcludeArchitecture parameter

3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-1909/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-1909/Dockerfile, 4.8/sdk/windowsservercore-ltsc2016/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile, README.sdk.md, eng/vs-info.json, manifest.json
Updates the SDK Dockerfiles to reference the newly released tools in VS 16.5.
Related to https://github.com/microsoft/dotnet-framework-docker/issues/534
=> Reference VS 16.5 tools

3.5/sdk/windowsservercore-1903/Dockerfile, 3.5/sdk/windowsservercore-ltsc2016/Dockerfile, 3.5/sdk/windowsservercore-ltsc2019/Dockerfile, 4.8/sdk/windowsservercore-1903/Dockerfile, 4.8/sdk/windowsservercore-ltsc2016/Dockerfile, 4.8/sdk/windowsservercore-ltsc2019/Dockerfile, README.sdk.md, eng/nuget-info.json, manifest.json, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.8/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.8/dotnetapp-4.8.sln, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.7.2/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.7.2/SimpleWebApplication.sln, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.8/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.8/SimpleWebApplication.sln
An unintended breaking change occurred when including the VS 16.5 tools in the SDK images (https://github.com/microsoft/dotnet-framework-docker/pull/543).  When attempting to run `nuget restore` on a solution file, it would cause the following error:
```
Exception has been thrown by the target of an invocation. The project file could not be loaded. Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
This issue can be resolved by upgrading the NuGet client to a version >= 4.8.2.  After evaluating the known issues for the NuGet client releases, it was decided to go with the latest 4.x release, 4.9.4, since there appear to be no known issues …
=> Update 4.x NuGet client to 4.9.4

3.5/aspnet/windowsservercore-1903/Dockerfile, 3.5/aspnet/windowsservercore-1909/Dockerfile, 3.5/aspnet/windowsservercore-ltsc2016/Dockerfile, 3.5/aspnet/windowsservercore-ltsc2019/Dockerfile, 4.6.2/aspnet/windowsservercore-ltsc2016/Dockerfile, 4.7.1/aspnet/windowsservercore-ltsc2016/Dockerfile, 4.7.2/aspnet/windowsservercore-ltsc2016/Dockerfile, 4.7.2/aspnet/windowsservercore-ltsc2019/Dockerfile, 4.7/aspnet/windowsservercore-ltsc2016/Dockerfile, 4.8/aspnet/windowsservercore-1903/Dockerfile, 4.8/aspnet/windowsservercore-1909/Dockerfile, 4.8/aspnet/windowsservercore-ltsc2016/Dockerfile, 4.8/aspnet/windowsservercore-ltsc2019/Dockerfile
The latest release of IIS ServiceMonitor contains a fix for [https://github.com/microsoft/IIS.ServiceMonitor/issues/32](https://github.com/microsoft/IIS.ServiceMonitor/issues/32), which is very annoying issue. @gislikonrad even ported ServiceMonitor to .NET to have it fixed: [https://github.com/SOLIDSoftworks/iis-service-monitor](https://github.com/SOLIDSoftworks/iis-service-monitor)
=> Update ServiceMonitor version to 2.0.1.10

documentation/guiding-principles.md, documentation/tagging-guidelines.md
These are similar to the [guiding principles](https://github.com/dotnet/dotnet-docker/blob/master/documentation/guiding-principles.md) we have for the .NET Core Docker repo with a few repo specific adjustments.
The primary piece I wanted to get documented is the tagging strategy.
=> Add guiding principles documentation

src/aspnet/3.5/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
Even though the build is broken due to the TLS requirement of dist.nuget.org, I felt it was appropriate to update _all_ cases where the Server 2016 Dockerfiles download files.  This ensures that any potential future TLS changes from those domains won't break the build.
Fixes #598
=> Make use of TLS 1.2 for downloads

src/runtime/3.5/windowsservercore-1903/Dockerfile, src/runtime/3.5/windowsservercore-1909/Dockerfile, src/runtime/3.5/windowsservercore-2004/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile, src/runtime/4.6.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile, src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-1903/Dockerfile, src/runtime/4.8/windowsservercore-1909/Dockerfile, src/runtime/4.8/windowsservercore-2004/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
Current references to Windows images are using multi-arch tags like `mcr.microsoft.com/windows/servercore:1903`.  Updating the tags to be concrete, architecture-specific tags by appending `-amd64` to the tag names to be future-proofed and explicit of the desired architecture.
=> Use concrete tags for base Windows images

eng/pipelines/dotnet-framework-pr-no-cache.yml
Defines a new pipeline YAML file that is intended to be used to validate PRs without caching enabled. The pipeline should only build/test a subset of the images. Rather than defining that subset within the YAML, I felt it more appropriate to define it in the variables of the build definition in AzDO where it can be more easily adjusted as necessary.
The proposed path to set for the build is the following:
```
--path 'src/*/4.8/windowsservercore-2004'
```
This pipeline is configured to be triggered only by changes to the eng and tests folders. A change to the src folder would likely end up causing a cache miss in the existing PR pipeline so this one wouldn't need to run in that case. The primary use case for this pipeline is to validate infrastructure changes in the eng folder.
Fixes #642
=> Pipeline to validate PR without caching

README.aspnet.md, README.runtime.md, README.samples.md, README.sdk.md, README.wcf.md, eng/mcr-tags-metadata-templates/aspnet-tags.yml, eng/mcr-tags-metadata-templates/runtime-tags.yml, eng/mcr-tags-metadata-templates/samples-tags.yml, eng/mcr-tags-metadata-templates/sdk-tags.yml, eng/mcr-tags-metadata-templates/wcf-tags.yml, eng/nuget-info.json, manifest.json, manifest.samples.json, src/aspnet/3.5/windowsservercore-2009/Dockerfile, src/aspnet/4.8/windowsservercore-2009/Dockerfile, src/runtime/3.5/windowsservercore-2009/Dockerfile, src/runtime/4.8/windowsservercore-2009/Dockerfile, src/sdk/3.5/windowsservercore-2009/Dockerfile, src/sdk/4.8/windowsservercore-2009/Dockerfile, src/wcf/4.8/windowsservercore-2009/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/OsVersion.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/clickonce-3.5/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/clickonce-4.8/Dockerfile
Related to https://github.com/microsoft/dotnet-framework-docker/issues/647
Fixes https://github.com/microsoft/dotnet-framework-docker/issues/646 by changing the 2009 Dockerfiles to use the default cmd shell instead of PowerShell.
Related to https://github.com/microsoft/dotnet-framework-docker/issues/650 by not declaring a `4.8-3.5` tagging pattern for the 2009 tags.
=> Add Dockerfiles for Windows, version 2009 

README.aspnet.md, README.runtime.md, README.sdk.md, README.wcf.md, eng/readme-templates/README.md
=> Clarify 3.5 compatibility with 3.0 and 2.0

eng/models/NuGetInfo.cs, eng/nuget-info.json, eng/update-dependencies/DependencyUpdater.cs, src/sdk/3.5/windowsservercore-1909/Dockerfile, src/sdk/3.5/windowsservercore-2004/Dockerfile, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-1909/Dockerfile, src/sdk/4.8/windowsservercore-2004/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Fixes #678
These changes include NuGet 5.8 in the SDK in order to address the incompatibilities introduced by VS 16.8 build tools with older versions of NuGet.  NuGet 5.8 is included as an additional installation that developers can optionally use in order to workaround this incompatibility.  The existing versions of NuGet in the SDK is not being changed at this time in order to avoid potential breaking changes associated with such an upgrade.
=> Include NuGet 5.8 in SDK as additional version

eng/common/templates/variables/docker-images.yml, eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1, eng/dockerfile-templates/wcf/Dockerfile, manifest.json, tests/Microsoft.DotNet.Framework.Docker.Tests/GeneratedArtifactTests.cs
This is the first phase of introducing Dockerfile templates.  The other variants such as aspnet, runtime, and sdk will be added if deemed valuable in subsequent PRs.
Related to #616
=> Add infra to generate wcf Dockerfiles from templates

eng/update-dependencies/DependencyUpdater.cs, src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile, src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.8/windowsservercore-1909/Dockerfile, src/aspnet/4.8/windowsservercore-2004/Dockerfile, src/aspnet/4.8/windowsservercore-20H2/Dockerfile, src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile, src/runtime/4.6.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile, src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-1909/Dockerfile, src/sdk/3.5/windowsservercore-2004/Dockerfile, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-1909/Dockerfile, src/sdk/4.8/windowsservercore-2004/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
Updates the usage of `ENV name value` syntax to `ENV name=value`.
Fixes #695
=> Remove usage of deprecated syntax for ENV instruction

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.versions.json, src/sdk/3.5/windowsservercore-1909/Dockerfile, src/sdk/3.5/windowsservercore-2004/Dockerfile, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-1909/Dockerfile, src/sdk/4.8/windowsservercore-2004/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
Updates all the SDK images to use the latest NuGet CLI version.
This implements the rest of the phased plan for #704.
Fixes https://github.com/microsoft/dotnet-framework-docker/issues/678
=> Use common NuGet CLI version

eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj, eng/update-dependencies/NuGet.config
Attempting to restore projects for `Microsoft.DotNet.Framework.UpdateDependencies.csproj` on a machine without cached NuGet packages will result in the following error:
```
/usr/share/dotnet/sdk/5.0.201/NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json. [/home/vsts/work/1/s/eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj]
/usr/share/dotnet/sdk/5.0.201/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/home/vsts/work/1/s/eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj]
/usr/share/dotnet/sdk/5.0.201/NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation …
```
=> Remove dependency on dotnet.myget.org NuGet feed

eng/update-dependencies/NuGet.config
My changes for https://github.com/microsoft/dotnet-framework-docker/pull/747 were incomplete.  I don't know what happened when testing locally but the `Microsoft.DotNet.VersionTools` package is stored in the `dotnet-eng` feed, not the `dotnet-public`.  Fixed the nuget.config file.
=> Add dotnet-eng feed for VersionTools package

tests/Microsoft.DotNet.Framework.Docker.Tests/projects/NuGet.config, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.7.1/.nuget/NuGet.config, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.7.2/.nuget/NuGet.config, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.7/.nuget/NuGet.config, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/webapp-4.8/.nuget/NuGet.config
Consolidates all the NuGet.config files used by test projects into one file which conforms to NuGet config policy.
=> Define NuGet.config with <clear> element

eng/dockerfile-templates/aspnet/Dockerfile, eng/dockerfile-templates/aspnet/Dockerfile.pre20H2, src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.7.2/windowsservercore-ltsc2019/Dockerfile, src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.8/windowsservercore-2004/Dockerfile, src/aspnet/4.8/windowsservercore-20H2/Dockerfile, src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile, src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs
=> Update the Roslyn to 3.6.0

eng/pipelines/cg-detection.yml
Defines a pipeline that runs through component governance whenever a commit is made.  This will cause all projects in the repo to be built and their assets scanned by component governance.
=> Add CG detection pipeline

eng/dockerfile-templates/runtime/Dockerfile.ltsc2016, src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
The URLs being used for downloading the runtime installers are broken due to recent changes in Download Center.  These changes update the URLs to the latest, as defined in https://dotnet.microsoft.com/download/dotnet-framework.
=> Update download URLS for runtime installers

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.versions.json, src/sdk/3.5/windowsservercore-2004/Dockerfile, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-2004/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
Upgrades the SDK Dockerfiles to VS 2022 tools. Note that the `Microsoft.VisualStudio.Workload.NetCoreBuildTools` VS component no longer exists. There isn't a direct replacement; instead, the individual sub-components are now directly referenced. 
Related to https://github.com/microsoft/dotnet-framework-docker/issues/844
=> Updates for VS 2022

build-and-test.ps1, eng/dockerfile-templates/runtime/Dockerfile, manifest.versions.json, src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2022/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTestHelper.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SkippableTheoryAttribute.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.8/Program.cs, tests/tests.sln
Applies the patch for 4.8's support of container limits (i.e. Docker's `--cpus` and `--memory` options).
=> Apply patch for supporting container limits

tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTestHelper.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs, tests/Microsoft.DotNet.Framework.Docker.Tests/SkippableTheoryAttribute.cs
When running tests locally and not specifying the `-Version` filter to the `build-and-test.ps1` script, it will cause the ContainerLimits test to be run for unsupported versions, causing failures.
The test is not skipped because the logic in the `SkippableTestAttribute` accounts for the wildcard scenario, which this scenario is when the Version value is set to `*` by default. The tests are designed to run the scenarios defined by the version matrix as defined by: https://github.com/microsoft/dotnet-framework-docker/blob/98002c0d20a95c84a790dab8d07783728a24edbe/tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs#L17-L34
The purpose of the `SkippableTestAttribute` is to reflect this same version matrix, not to further refine it. This is to workaround the limitation of …
=> Fix container limits tests failing on local run

eng/pipelines/update-readmes.yml
`Hosted Ubuntu 1604` is no longer a supported pool. Updating to built-in variable for the default pool.
=> Fix update-readmes pipeline pool

eng/dockerfile-templates/runtime/Dockerfile, src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile
=> Apply 4.8 container limits patch to 3.5 Dockerfile for WS 2022

eng/common/templates/variables/docker-images.yml, eng/dockerfile-templates/runtime/Dockerfile, src/runtime/4.8/windowsservercore-ltsc2022/Dockerfile
Needing to revert back the version of Image Builder because some of the changes to support arch "variant" aren't working on the 2016 machines.
Also fixing the Dockerfile generation for 2022.
=> Fix build issues

eng/dockerfile-templates/sdk/Dockerfile, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Related to https://github.com/dotnet/release/issues/410
Execution of `ngen update` in the sdk Dockerfiles is failing because an arm64 version of MSBuild is mistakenly queued for ngen. This results in the errors:
`Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\arm64\MSBuild.exe because this image is not a valid Win32 application.`
`An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)`
As a workaround, I've uninstalled it from the ngen queue.
Update: This also applies to several variations of testhost.exe from VS TestAgent.
=> Ngen workaround for arm64 version of MSBuild and TestHost

eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
Applies the same workarounds from https://github.com/microsoft/dotnet-framework-docker/pull/952 to the sdk Dockerfiles for WS 2016.
Eventually, we should update the templates to share more of this content to avoid issues of not keeping them in sync.
=> Apply ngen workarounds to sdk for WS 2016

.mcr/portal/README.aspnet.portal.md, .mcr/portal/README.runtime.portal.md, .mcr/portal/README.samples.portal.md, .mcr/portal/README.sdk.portal.md, .mcr/portal/README.wcf.portal.md, README.aspnet.md, README.md, README.runtime.md, README.samples.md, README.sdk.md, README.wcf.md, eng/common/templates/variables/docker-images.yml, eng/readme-templates/About.md, eng/readme-templates/About.product-family.md, eng/readme-templates/FeaturedTags.md, eng/readme-templates/Get-GeneratedReadmes.ps1, eng/readme-templates/README.mcr.md, eng/readme-templates/README.md, eng/readme-templates/RelatedRepos.md, eng/readme-templates/Support.md, eng/readme-templates/Use.aspnet.md, eng/readme-templates/Use.md, eng/readme-templates/Use.product-family.md, eng/readme-templates/Use.runtime.md, eng/readme-templates/Use.samples.md, eng/readme-templates/Use.sdk.md, eng/readme-templates/Use.wcf.md, manifest.json, manifest.samples.json
* Updates the manifest to conform to the new schema defined by https://github.com/dotnet/docker-tools/pull/1001.
* Defines new readme files to be used for the MCR portal.
* Refactors the readme templates to enable more common content between the GH and MCR readmes.
I've moved the Version Compatibility section out of the Tags section and into the Usage section. This was done because the MCR readmes don't have a Tags section.
=> Generate readmes for MCR portal

eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj, tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
Updates the projects in this repo to reference the latest versions of their package dependencies. The only one not included in this is [System.CommandLine](https://github.com/microsoft/dotnet-framework-docker/issues/966) which has breaking changes that need to be accounted for.
=> Upgrade package dependencies

NuGet.config
Defines a default NuGet.config file at the repo root for a couple reasons:
* An issue was discovered with restoring NuGet packages for the test project on a newly provisioned machine because its %APPDATA%\NuGet\NuGet.config file did not contain any package sources. Since the repo didn't define its own NuGet.config listing any package sources either, NuGet couldn't find any packages to restore from and failed.
* For secure supply chain reasons, we need to be explicit about which NuGet feed is used.
=> Add default NuGet.config

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.versions.json, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile, tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
Updates the VS build tools to 17.3.
For now, this is targeting the Preview version of 17.3 since it's not yet released. This will be updated before merging on release day.
To allow for things to work against a Preview version, I needed to make the following changes:
* Explicitly set the `--install-path` option for the installer. Otherwise, the installer would install to the `%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Preview` path for both Test Agent and Build Tools, causing a conflict.
* Logic to parse preview version of .NET installation in the tests.
* Logic to gracefully handle preview versions when using vswhere utility.
The upgrade to 17.3 also allowed the removal of some GAC workarounds now that the underlying issues have been fixed.
=> VS 17.3 updates

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, src/sdk/3.5/windowsservercore-20H2/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-20H2/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Visual Studio 2022 changed the  "Developer Command Prompt for VS 2022" PATH setting to reference the 64-bit copy of MSBuild folder, corresponding with the change to make devenv.exe/Visual Studio itself a 64-bit process.
I think the Docker container experience should match, but there is some risk here: some projects that build with a 32-bit MSBuild will fail with a 64-bit one. Those projects won't build on the standard VS command line, so there should be very few, but it's worth considering the impact (and I don't have a great way to quantify either way).
=> Put 64-bit MSBuild on PATH

tests/Microsoft.DotNet.Framework.Docker.Tests/projects/NuGet.config
This NuGet.config file is getting flagged in our builds by the NuGet security analysis because it's referencing nuget.org feed instead of the Azure Artifact Feed. But this file is actually unneeded and not used by the tests so I'm deleting it.
=> Remove unneeded test NuGet.config

eng/dockerfile-templates/runtime/Dockerfile, eng/dockerfile-templates/runtime/Dockerfile.ltsc2016, manifest.versions.json, src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile
This simplifies the runtime Dockerfile templates, allowing them to make use of variables that define the URLs to install the various versions of .NET Fx.
There was an inconsistency discovered for 4.8. The URL used for 4.8 was different between WSC 2019 and WSC 2016 Dockerfiles. The WSC 2016 Dockerfile was using a more current URL of that file. This different didn't have a functional difference since the patch was still being applied on top of the base installer. But at least now this makes things current and consistent.
=> Refactor Dockerfile templates to use .NET Fx URL variables

eng/dockerfile-templates/runtime/Dockerfile, eng/dockerfile-templates/runtime/Dockerfile.ltsc2016, eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.versions.json
In an effort to simplify the Dockerfile templates and prepare for the addition of .NET Fx 4.8.1, these changes refactor the templates to avoid the need for `if..else` logic when referencing the KB patch info variables.
The naming of the variables was consistent and didn't directly correspond to available template variables, which caused the templates to be very specific to which variable they needed to reference.
These changes add more specificity to the variable names so that the templates can simply use the template `PRODUCT_VERSION` variable when needing to construct the variable name to reference.
=> Refactor patch variable usage in Dockerfile templates

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
This is a continuation of the changes in https://github.com/microsoft/dotnet-framework-docker/pull/988. That PR missed the hard-coded 4.8 URLs in the 3.5 SDK Dockerfiles. Again, same comment about the URL inconsistency with 4.8 that was mentioned in the previous PR applies here.
Confirmed there are no other hard-coded references to `download.visualstudio.microsoft.com` in the templates.
=> Refactor SDK Dockerfile templates to use .NET Fx URL variables

eng/pipelines/dotnet-framework-samples.yml, eng/pipelines/dotnet-framework.yml
The changes in https://github.com/microsoft/dotnet-framework-docker/pull/1001 ended up renaming the GitHub repo endpoint name for internal pipelines when it should instead have only applied them to the public pipelines. I've reverted the change for the affected internal pipelines.
=> Revert pipeline repo endpoint name for internal pipelines

eng/common/Install-DotNetSdk.ps1
Changes to the channel classification of .NET versions has caused "Current" channel to install .NET 5. Removing the channel parameter fixes this.
=> .NET install script workaround

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
.NET Core 3.1 is EOL as of Dec. 13, 2022 so it is being removed from the SDK Dockerfiles.
Fixes #994
=> Remove .NET Core 3.1 from SDK Dockerfiles

eng/common/Install-DotNetSdk.ps1, eng/common/templates/variables/docker-images.yml, eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj, tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
Includes changes from https://github.com/microsoft/dotnet-framework-docker/pull/1040 as well as updates to .NET 7.0 to fix the test project failure in that PR. I don't have permissions to push to dotnet-docker-bot's branch so I'm opening this as a separate PR.
=> Update eng/common with latest and update to .NET 7.0

README.sdk.md, eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.datestamps.json, manifest.versions.json, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Non-functional whitespace was intentionally added to the SDK Dockerfiles to cause them to have a new git commit. This is to workaround the pipeline image caching logic. For this release we want to reuse all existing images except for the SDK, without rebuilding them. So we want caching to be enabled but we need to cause the SDK Dockerfiles to be rebuilt. This is done by having them be associated with a new git commit, causing a cache miss and rebuilding the Dockerfiles.
Related to https://github.com/dotnet/release/issues/473
=> Updates for VS 17.5 release

eng/common/templates/jobs/build-images.yml, eng/common/templates/stages/build-test-publish-repo.yml
Now that the Dockerfiles are in sync with the templates from https://github.com/microsoft/dotnet-framework-docker/pull/1080, we can re-enable the prebuild validation step that was disabled by https://github.com/microsoft/dotnet-framework-docker/pull/1074.
Fixes https://github.com/microsoft/dotnet-framework-docker/issues/1075
=> Re-enable prebuild validation step

eng/common/templates/jobs/build-images.yml, eng/common/templates/jobs/copy-base-images.yml, eng/common/templates/jobs/generate-matrix.yml, eng/common/templates/jobs/post-build.yml, eng/common/templates/jobs/publish.yml, eng/common/templates/jobs/test-images-linux-client.yml, eng/common/templates/jobs/test-images-windows-client.yml, eng/common/templates/jobs/wait-for-ingestion.yml, eng/common/templates/stages/build-test-publish-repo.yml, eng/common/templates/stages/dotnet/build-test-publish-repo.yml, eng/common/templates/steps/copy-base-images.yml, eng/common/templates/steps/init-docker-linux.yml, eng/common/templates/steps/init-docker-windows.yml, eng/common/templates/steps/publish-artifact.yml, eng/common/templates/steps/publish-readmes.yml, eng/common/templates/steps/set-dry-run.yml, eng/common/templates/steps/test-images-linux-client.yml, eng/common/templates/steps/test-images-windows-client.yml, eng/common/templates/steps/validate-image-sizes.yml, eng/common/templates/variables/common.yml, eng/common/templates/variables/docker-images.yml, eng/common/templates/variables/dotnet/build-test-publish.yml, eng/common/templates/variables/dotnet/common.yml, eng/pipelines/dotnet-framework-samples.yml, eng/pipelines/dotnet-framework.yml
This PR contains changes from https://github.com/microsoft/dotnet-framework-docker/pull/1112
Part of https://github.com/dotnet/dotnet-docker-internal/issues/4475
Server 2016 images have pipeline templates support now. This is a draft PR since validation is still running but I am fairly confident in the changes. I will submit a follow-up PR to docker-tools for the eng/common changes once validation is successful.
2016 test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2409603&view=results
2019 & 2022 test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2409701&view=results
Samples test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2409869&view=results
=> Move dotnet-framework-docker pipelines to 1ES Pipeline templates

eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Related to https://github.com/dotnet/dotnet-docker/issues/5336.
When making these changes I discovered the ltsc2016 sdk images were missing the 8.0 runtime so I added it.
=> Remove eol 7.0 runtime and add missing 8.0 runtime

.portal-docs/docker-hub/README.aspnet.md, .portal-docs/docker-hub/README.runtime.md, .portal-docs/docker-hub/README.samples.md, .portal-docs/docker-hub/README.sdk.md, .portal-docs/docker-hub/README.wcf.md, README.aspnet.md, README.md, README.runtime.md, README.samples.md, README.sdk.md, README.wcf.md, eng/readme-templates/Url.md
Updates Docker Hub links to match the new URL format. The old links still redirect to the new one but might as well avoid that.
=> Use new URL format for Docker Hub pages

.github/ISSUE_TEMPLATE/new-windows-release.md
Related to https://github.com/dotnet/dotnet-docker/issues/5430
=> Move new windows release issue template from dotnet/release

.github/ISSUE_TEMPLATE/workflows/markdownlint-problem-matcher.json, .github/ISSUE_TEMPLATE/workflows/markdownlint.yml, .markdownlint.json
Related to https://github.com/dotnet/dotnet-docker/issues/5316
This initial set of changes just adds the linter action but disables numerous rules. Once enabled I will open follow-up PRs to address the syntax violations.
The linter action was copied from [dotnet/runtime](https://github.com/dotnet/runtime/blob/main/.github/workflows/markdownlint.yml).
=> Add Markdown linter GH action

.markdownlint.json, .portal-docs/docker-hub/README.aspnet.md, .portal-docs/docker-hub/README.runtime.md, .portal-docs/docker-hub/README.samples.md, .portal-docs/docker-hub/README.sdk.md, .portal-docs/docker-hub/README.wcf.md, .portal-docs/mar/README.aspnet.portal.md, .portal-docs/mar/README.runtime.portal.md, .portal-docs/mar/README.samples.portal.md, .portal-docs/mar/README.sdk.portal.md, .portal-docs/mar/README.wcf.portal.md, README.aspnet.md, README.md, README.runtime.md, README.samples.md, README.sdk.md, README.wcf.md, eng/common/templates/variables/docker-images.yml, eng/readme-templates/About.product-family.md, eng/readme-templates/DefaultLayout.md, eng/readme-templates/GitHub.header.md, eng/readme-templates/README.dockerhub.md, eng/readme-templates/README.github.md, eng/readme-templates/README.mcr.md, eng/readme-templates/RelatedRepos.md, eng/readme-templates/RepoList.md, eng/readme-templates/ReposProvider.md, eng/readme-templates/Use.aspnet.md, eng/readme-templates/Use.wcf.md
Related to https://github.com/dotnet/dotnet-docker/issues/5316
This PR is the last part of a series of changes to address various markdown syntax violations.
1. I ported the ReposProvider readme template infra from dotnet-docker to eliminate duplication that would otherwise exist with these changes.
2. I discovered we were referencing a dead link to a dotnet-nightly product family repo that doesn't exist.  I removed the dotnet-nightly related repos section of the readmes
3. To be consistent with dotnet-docker I added the product family to the related repos section of the readmes.
=> Fix markdown syntax violations

eng/pipelines/cg-detection.yml, eng/pipelines/update-readmes.yml
Fixes https://github.com/microsoft/dotnet-framework-docker/issues/1170
Closes https://github.com/dotnet/docker-tools/issues/1227
[CG detection test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2544942&view=results)
[Update Readmes test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2544960) (I manually cancelled once it properly initialized and began running)
=> Update pipelines to use `eng/common` 1es templates

README.sdk.md, eng/dockerfile-templates/sdk/Dockerfile, eng/dockerfile-templates/sdk/Dockerfile.ltsc2016, manifest.datestamps.json, src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
Fixes #1180. This should not be merged until .NET 9 is officially released.
=> Add .NET 9 to SDK images

eng/dockerfile-templates/sdk/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile, src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8.1/windowsservercore-ltsc2022/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile, src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile
See https://github.com/dotnet/dotnet-docker/issues/6051#issuecomment-2474763943
=> Remove .NET 6 from SDK images

.github/workflows/check-markdown-links.yml
Related: https://github.com/dotnet/dotnet-docker/pull/6132
=> Downgrade linkspector GitHub action to Ubuntu 22.04 due to a bug

eng/common/Invoke-ImageBuilder.ps1, eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1, eng/readme-templates/Get-GeneratedReadmes.ps1
When running the current scripts on Windows, the script tries to copy files from a container that doesn't exist because Invoke-ImageBuilder.ps1 does not create a container on Windows. As a result it throws some warnings/errors and the command "fails" even though it does what you want:
```pwsh
PS> pwsh .\eng\readme-templates\Get-GeneratedReadmes.ps1
...
Executing: 'docker cp ImageBuilder-20250228105133:/repo/README.aspnet.md C:\...\dotnet-framework-docker/'
Error response from daemon: No such container: ImageBuilder-20250228105133
PS> $?
False
```
This PR skips the copy on Windows. I made sure it works on all three of Windows PowerShell, PowerShell Core on Windows, and PowerShell Core on Linux.
=> Fix warnings in template generation scripts on Windows

eng/dockerfile-templates/aspnet/Dockerfile, eng/dockerfile-templates/aspnet/Dockerfile.3.5.pre20H2, eng/dockerfile-templates/aspnet/Dockerfile.pre20H2, manifest.versions.json
This PR centralizes the ServiceMonitor.exe download URL used in multiple templates. Related: #1221
=> Move ServiceMonitor download URL into versions file
