microsoft/dotnet-framework-docker

README.md

[README] Fix 3.5 sample Dockerfile

---

3.5/Dockerfile

Also tweaked the format to have one cmd per line in order to make it more readable.
cc @richlander, @shirhatti

[3.5 Dockerfile] Added logic to delete build directory

---

README.md

- Updated README to match Docker norms
- Updated READ to match microsoft/dotnet README
- Links still need to be updated to samples repo, which is in progress -- will block on merging before that
/cc @kendrahavens @michaelsimons @BillWagner @mairaw

Update README to match Docker norms

---

README.md

Changed relative Dockerfile link in readme to be absolute

---

3.5/Dockerfile

Install framework 3.5 and patches

---

README.md

Fixes #11. ReadMe uses wrong slashes in suggested Dockerfile.

Fix Dockerfile in ReadMe

---

4.7.1/Dockerfile
README.md

Waiting for .NET Framework 4.7.1 to ship.
Fixes #26

Add .NET Framework 4.7.1 image

---

4.7.1-windowsservercore-1709/build/Dockerfile

Update Nuget in 1709 build Dockerfile to match ltsc2016

---

3.5-windowsservercore-1709/build/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile

Add 3.5 build images

---

manifest.json
scripts/Get-TagsDocumentation.ps1

Also added Get-TagsDocumentation.ps1 script.

Add manifest.json in order to support using image-builder tools on repo

---

3.5-windowsservercore-ltsc2016/runtime/Dockerfile
4.6.2-windowsservercore-ltsc2016/runtime/Dockerfile
4.7-windowsservercore-ltsc2016/runtime/Dockerfile
4.7.1-windowsservercore-ltsc2016/runtime/Dockerfile

Updated ltsc2016 based Dockerfiles to use explicit ltsc2016 base image

---

build-pipeline/README.md
build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json
build-pipeline/pipeline.json

Triggers aren't hooked-up.  We will manually trigger when we want a build.

Introduce build-pipeline for building repo

---

3.5-windowsservercore-1709/build/Dockerfile
3.5-windowsservercore-1709/runtime/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile
3.5-windowsservercore-ltsc2016/runtime/Dockerfile
4.6.2-windowsservercore-ltsc2016/runtime/Dockerfile
4.7-windowsservercore-ltsc2016/runtime/Dockerfile
4.7.1-windowsservercore-1709/build/Dockerfile
4.7.1-windowsservercore-1709/runtime/Dockerfile
4.7.1-windowsservercore-ltsc2016/build/Dockerfile
4.7.1-windowsservercore-ltsc2016/runtime/Dockerfile

 Switched to use backtick escape character in Dockerfiles

---

.gitignore
build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json
build-pipeline/pipeline.json
manifest.json
tests/Microsoft.DotNet.Framework.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/ImageDescriptor.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-3.5/App.config
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-3.5/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-3.5/Program.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-3.5/dotnetapp-3.5.csproj
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.6.2/App.config
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.6.2/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.6.2/Program.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.6.2/dotnetapp-4.6.2.csproj
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7.1/App.config
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7.1/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7.1/Program.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7.1/dotnetapp-4.7.1.csproj
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7/App.config
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7/Program.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/projects/dotnetapp-4.7/dotnetapp-4.7.csproj
tests/run-tests.ps1
tests/tests.sln

Initial version of validation tests

---

build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json

This adds support for publishing to a private Docker Registry

Update ImageBuilder to latest

---

3.5-windowsservercore-1709/runtime/Dockerfile
3.5-windowsservercore-ltsc2016/runtime/Dockerfile

Update 3.5 runtime Dockerfiles with 2018-01 cumulative patch URL.
Cc @richlander @mcy94w

2018-01 patch URL for 3.5 runtime

---

build-and-test.ps1
netci.groovy

Fixes https://github.com/Microsoft/dotnet-framework-docker/issues/79

Cleanup Docker assets in CI

---

3.5-windowsservercore-1709/build/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile
4.7.1-windowsservercore-1709/build/Dockerfile
4.7.1-windowsservercore-ltsc2016/build/Dockerfile
README.dotnet-framework-build.md
manifest.json

Related to #63
Related to #90 
Replaces #80 - this PR is against the dev branch so that a series of fixed can be batched.

Update build Dockerfiles to ngen assemblies queued by VS installers

---

3.5-windowsservercore-1709/build/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile
4.7.1-windowsservercore-1709/build/Dockerfile
4.7.1-windowsservercore-ltsc2016/build/Dockerfile

Update VS components to 15.5

---

3.5-windowsservercore-1709/runtime/Dockerfile
3.5-windowsservercore-ltsc2016/runtime/Dockerfile

.NET 3.5 Dockerfile updates for February 2018 patch.

Update KB number and URL for February 2018

---

README.dotnet-framework-build.md

Update tags in build readme that are out of date

---

README.dotnet-framework-build.md
README.dotnet-framework.md
scripts/Get-TagsDocumentation.ps1

Update readmes to correctly reference Windows Server version 1709

---

3.5-windowsservercore-1709/build/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile
4.7.1-windowsservercore-1709/build/Dockerfile
4.7.1-windowsservercore-ltsc2016/build/Dockerfile
README.dotnet-framework-build.md
manifest.json

Fixes https://github.com/Microsoft/dotnet-framework-docker/issues/106

Update VS components in builder images to 15.6

---

build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json

Adjust build timeouts

---

README.dotnet-framework-build.md
README.dotnet-framework.md
manifest.json

Note this is going into the dev branch.
Fixes #111

Add patch specific runtime tags

---

3.5-windowsservercore-1709/runtime/Dockerfile
3.5-windowsservercore-ltsc2016/build/Dockerfile
3.5-windowsservercore-ltsc2016/runtime/Dockerfile
4.7-windowsservercore-ltsc2016/runtime/Dockerfile
4.7.1-windowsservercore-ltsc2016/runtime/Dockerfile
README.dotnet-framework-build.md
README.dotnet-framework.md
manifest.json

 Apply latest cumulative updates

---

build-and-test.ps1
build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json
build-pipeline/pipeline.samples.json

Updates to build samples

---

3.5-windowsservercore-1803/runtime/Dockerfile
3.5-windowsservercore-1803/sdk/Dockerfile
4.7.2-windowsservercore-1803/runtime/Dockerfile
4.7.2-windowsservercore-1803/sdk/Dockerfile
README.md
build-pipeline/dotnet-framework-docker-post-image-build.json
build-pipeline/dotnet-framework-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-1804-amd64-images.json
build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json
build-pipeline/pipeline.json
manifest.json
tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs

This will get merged together with https://github.com/Microsoft/dotnet-framework-docker/pull/135
@dotnet-bot skip ci please

Add support for RS4

---

3.5-windowsservercore-1803/sdk/Dockerfile
4.7.2-windowsservercore-1803/sdk/Dockerfile

Fix broken buildtools link

---

build-pipeline/dotnet-framework-docker-windows-ltsc2016-amd64-images.json

Update build queue used by ltsc2016 build legs

---

.vsts-pipelines/phases/build-amd64.yml
.vsts-pipelines/phases/copy-images.yml

Adjust build path filters to work for samples

---

3.5/sdk/windowsservercore-1709/Dockerfile
3.5/sdk/windowsservercore-1803/Dockerfile
3.5/sdk/windowsservercore-ltsc2016/Dockerfile
4.7.1/sdk/windowsservercore-1709/Dockerfile
4.7.1/sdk/windowsservercore-ltsc2016/Dockerfile
4.7.2/sdk/windowsservercore-1709/Dockerfile
4.7.2/sdk/windowsservercore-1803/Dockerfile
4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile

Just following the formatting standards used in the other dockerfiles.
Thanks so much for all the great work :)

feat(formatting): Improve code readability with multiline

---

.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/copy-images.yml
.vsts-pipelines/phases/publish-finalize.yml
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
3.5/sdk/windowsservercore-ltsc2019/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile
README.md
manifest.json
manifest.samples.json
netci.groovy
samples/README.DockerHub.md
tests/Microsoft.DotNet.Framework.Docker.Tests/ImageTests.cs

Add Windows Server 2019 images

---

.vsts-pipelines/steps/docker-cleanup-windows.yml
3.5/runtime/windowsservercore-1709/Dockerfile
3.5/runtime/windowsservercore-1803/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
4.6.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.1/runtime/windowsservercore-1709/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-1709/Dockerfile
4.7.2/runtime/windowsservercore-1803/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
build-and-test.ps1

Update Dockerfiles to reference Windows images from MCR

---

3.5/runtime/windowsservercore-1709/Dockerfile
3.5/runtime/windowsservercore-1803/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-1709/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.md
manifest.json

~~The 3.5-1803 image is not being updated due to a Windows issue.~~

Apply 1 b patch updates

---

3.5/runtime/windowsservercore-1709/Dockerfile
3.5/runtime/windowsservercore-1803/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-1709/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.md
manifest.json
samples/README.DockerHub.md
samples/README.md
samples/aspnetapp/Dockerfile
samples/aspnetapp/Dockerfile.windowsservercore-ltsc2016
samples/aspnetapp/README.md
samples/aspnetmvcapp/Dockerfile
samples/aspnetmvcapp/README.md
samples/dotnetapp/README.md
samples/wcfapp/README.md

CI is expected to fail until patched base images are published.

Apply 2b patch updates

---

README.md
samples/README.DockerHub.md
samples/README.md
samples/aspnetapp/README.md
samples/aspnetmvcapp/README.md
samples/dotnetapp/README.md
samples/wcfapp/README.md

Update readme 'Related Repos' with MCR repos

---

3.5/runtime/windowsservercore-1709/Dockerfile
3.5/runtime/windowsservercore-1803/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-1709/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.md
manifest.json

Fixes #229 
CI is expected to fail until updated OS images are available.

Apply 3B patch updates

---

README.md
README.runtime.md
README.samples.md
README.sdk.md
samples/README.md
samples/aspnetapp/README.md
samples/aspnetmvcapp/README.md
samples/dotnetapp/README.md
samples/wcfapp/Dockerfile.web
samples/wcfapp/README.md

Misc cleanup after migrating to MCR.

Replace old Docker Hub references with MCR references

---

3.5/runtime/windowsservercore-1803/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.runtime.md
README.sdk.md
manifest.json

Fixes #245 
@dotnet-bot skip CI please

Apply April patch updates

---

README.md
README.samples.md
README.sdk.md

Remove obsolete .NET Framework Docker documentation references

---

4.6.2/wcf/windowsservercore-ltsc2016/Dockerfile
4.7.1/wcf/windowsservercore-ltsc2016/Dockerfile
4.7.2/wcf/windowsservercore-1803/Dockerfile
4.7.2/wcf/windowsservercore-ltsc2016/Dockerfile
4.7.2/wcf/windowsservercore-ltsc2019/Dockerfile
4.7/wcf/windowsservercore-ltsc2016/Dockerfile
4.8/wcf/windowsservercore-1803/Dockerfile
4.8/wcf/windowsservercore-1903/Dockerfile
4.8/wcf/windowsservercore-ltsc2016/Dockerfile
4.8/wcf/windowsservercore-ltsc2019/Dockerfile

Fix indentation of WCF docker files.

---

3.5/aspnet/windowsservercore-1803/Dockerfile
3.5/aspnet/windowsservercore-1903/Dockerfile
3.5/aspnet/windowsservercore-ltsc2016/Dockerfile
3.5/aspnet/windowsservercore-ltsc2019/Dockerfile
4.6.2/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.1/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.2/aspnet/windowsservercore-1803/Dockerfile
4.7.2/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.2/aspnet/windowsservercore-ltsc2019/Dockerfile
4.7/aspnet/windowsservercore-ltsc2016/Dockerfile
4.8/aspnet/windowsservercore-1803/Dockerfile
4.8/aspnet/windowsservercore-1903/Dockerfile
4.8/aspnet/windowsservercore-ltsc2016/Dockerfile
4.8/aspnet/windowsservercore-ltsc2019/Dockerfile

Misc formatting cleanup within the aspnet Dockerfiles

---

eng/pipelines/dotnet-framework.yml

Adjusting build timeouts after upgrading build hardware

---

3.5/sdk/windowsservercore-1803/Dockerfile
3.5/sdk/windowsservercore-1903/Dockerfile
3.5/sdk/windowsservercore-ltsc2016/Dockerfile
3.5/sdk/windowsservercore-ltsc2019/Dockerfile
4.7.1/sdk/windowsservercore-ltsc2016/Dockerfile
4.7.2/sdk/windowsservercore-1803/Dockerfile
4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile
4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile
4.8/sdk/windowsservercore-1803/Dockerfile
4.8/sdk/windowsservercore-1903/Dockerfile
4.8/sdk/windowsservercore-ltsc2016/Dockerfile
4.8/sdk/windowsservercore-ltsc2019/Dockerfile

Updates the NuGet CLI version from 4.4.1 to 4.4.3.
Related to #413

Update NuGet CLI to latest patch version

---

3.5/aspnet/windowsservercore-1909/Dockerfile
3.5/runtime/windowsservercore-1909/Dockerfile
3.5/sdk/windowsservercore-1909/Dockerfile
4.8/aspnet/windowsservercore-1909/Dockerfile
4.8/runtime/windowsservercore-1909/Dockerfile
4.8/sdk/windowsservercore-1909/Dockerfile
4.8/wcf/windowsservercore-1909/Dockerfile
README.aspnet.md
README.runtime.md
README.samples.md
README.sdk.md
README.wcf.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/samples-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
eng/mcr-tags-metadata-templates/wcf-tags.yml
manifest.json
manifest.samples.json
samples/aspnetapp/deploy-container-to-aci.md
tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/OsVersion.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs

Add Dockerfiles for Windows Server Core 1909

---

README.aspnet.md
README.md
README.runtime.md
README.samples.md
README.sdk.md
samples/README.md
samples/aspnetapp/README.md
samples/aspnetmvcapp/README.md
samples/dotnetapp/README.md
samples/wcfapp/README.md

I think I got them all.
Fixes #449

Corrected references to WCF to use Foundation instead of Framework.

---

eng/models/LcuInfo.cs
eng/models/Microsoft.DotNet.Framework.Models.csproj
eng/models/NuGetInfo.cs
eng/models/VsInfo.cs
eng/update-dependencies/DependencyUpdater.cs
eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj
eng/vs-info.json
tests/Microsoft.DotNet.Framework.Docker.Tests/Config.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
tests/run-tests.ps1
tests/tests.sln

Add test to verify vswhere tool works in SDK images

---

4.6.2/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.1/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.2/aspnet/windowsservercore-ltsc2016/Dockerfile
4.7.2/aspnet/windowsservercore-ltsc2019/Dockerfile
4.7/aspnet/windowsservercore-ltsc2016/Dockerfile
4.8/aspnet/windowsservercore-1903/Dockerfile
4.8/aspnet/windowsservercore-1909/Dockerfile
4.8/aspnet/windowsservercore-ltsc2016/Dockerfile
4.8/aspnet/windowsservercore-ltsc2019/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs

* They are not needed.
Fixes #474

Remove escaping backslashes.

---

README.aspnet.md
README.md
README.runtime.md
README.samples.md
README.sdk.md
README.wcf.md

Add README Feedback links for MCR and VS Docker Tools

---

.github/ISSUE_TEMPLATE/releases/new-windows-release.md
.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md

Defines an issue template for the steps to take in preparation for a new version of Windows.
Related to dotnet/docker-tools#383

Issue template for new Windows release

---

3.5/runtime/windowsservercore-1903/Dockerfile
3.5/runtime/windowsservercore-1909/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
4.8/runtime/windowsservercore-ltsc2016/Dockerfile
4.8/runtime/windowsservercore-ltsc2019/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/513

Updates for 2B patches

---

3.5/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/533

Update 2016 for 3B Patch Tuesday changes

---

3.5/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/558

Updates for 4B release

---

3.5/runtime/windowsservercore-1903/Dockerfile
3.5/runtime/windowsservercore-1909/Dockerfile
3.5/runtime/windowsservercore-ltsc2016/Dockerfile
3.5/runtime/windowsservercore-ltsc2019/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2019/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
4.8/runtime/windowsservercore-1903/Dockerfile
4.8/runtime/windowsservercore-1909/Dockerfile
4.8/runtime/windowsservercore-ltsc2016/Dockerfile
4.8/runtime/windowsservercore-ltsc2019/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/575

Updates for 5B release

---

3.5/sdk/windowsservercore-1903/Dockerfile
3.5/sdk/windowsservercore-1909/Dockerfile
3.5/sdk/windowsservercore-ltsc2016/Dockerfile
3.5/sdk/windowsservercore-ltsc2019/Dockerfile
4.8/sdk/windowsservercore-1903/Dockerfile
4.8/sdk/windowsservercore-1909/Dockerfile
4.8/sdk/windowsservercore-ltsc2016/Dockerfile
4.8/sdk/windowsservercore-ltsc2019/Dockerfile
README.sdk.md
eng/vs-info.json
manifest.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/576

VS 16.6 tools update

---

3.5/aspnet/windowsservercore-2004/Dockerfile
3.5/runtime/windowsservercore-2004/Dockerfile
3.5/sdk/windowsservercore-2004/Dockerfile
4.8/aspnet/windowsservercore-2004/Dockerfile
4.8/runtime/windowsservercore-2004/Dockerfile
4.8/sdk/windowsservercore-2004/Dockerfile
4.8/wcf/windowsservercore-2004/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
eng/mcr-tags-metadata-templates/wcf-tags.yml
eng/nuget-info.json
manifest.json
tests/Microsoft.DotNet.Framework.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/OsVersion.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeOnlyImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/RuntimeSdkImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs
tests/Microsoft.DotNet.Framework.Docker.Tests/WcfImageTests.cs

Related to https://github.com/microsoft/dotnet-framework-docker/issues/559

Add Windows Server, version 2004 Dockerfiles

---

README.samples.md
eng/mcr-tags-metadata-templates/samples-tags.yml
manifest.samples.json

Related to https://github.com/microsoft/dotnet-framework-docker/issues/559

Add Server Core 2004 to samples build

---

3.5/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.1/runtime/windowsservercore-ltsc2016/Dockerfile
4.7.2/runtime/windowsservercore-ltsc2016/Dockerfile
4.7/runtime/windowsservercore-ltsc2016/Dockerfile
README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json

Updates for 6B release

---

README.aspnet.md
README.runtime.md
README.sdk.md
manifest.json

Set 4.8-3.5 shared tag as undocumented

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-1903/Dockerfile
src/runtime/3.5/windowsservercore-1909/Dockerfile
src/runtime/3.5/windowsservercore-2004/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-1903/Dockerfile
src/runtime/4.8/windowsservercore-1909/Dockerfile
src/runtime/4.8/windowsservercore-2004/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/610

Updates for 7B release

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-1903/Dockerfile
src/runtime/3.5/windowsservercore-1909/Dockerfile
src/runtime/3.5/windowsservercore-2004/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-1903/Dockerfile
src/runtime/4.8/windowsservercore-1909/Dockerfile
src/runtime/4.8/windowsservercore-2004/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/626

Updates for 8B release

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-1903/Dockerfile
src/runtime/3.5/windowsservercore-1909/Dockerfile
src/runtime/3.5/windowsservercore-2004/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-1903/Dockerfile
src/runtime/4.8/windowsservercore-1909/Dockerfile
src/runtime/4.8/windowsservercore-2004/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/634

9B servicing updates

---

build-and-test.ps1
tests/run-tests.ps1

Fixes dotnet/dotnet-docker#2261

Skip pre-build tests on Windows containers

---

src/sdk/3.5/windowsservercore-1903/Dockerfile
src/sdk/3.5/windowsservercore-1909/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-1903/Dockerfile
src/sdk/4.8/windowsservercore-1909/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs

Delete everything but vswhere from VS installers directory

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-1903/Dockerfile
src/runtime/3.5/windowsservercore-1909/Dockerfile
src/runtime/3.5/windowsservercore-2004/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-1903/Dockerfile
src/runtime/4.8/windowsservercore-1909/Dockerfile
src/runtime/4.8/windowsservercore-2004/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/643

Updates for 10B servicing release

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
README.aspnet.md
README.md
README.runtime.md
README.samples.md
README.sdk.md
README.wcf.md
eng/readme-templates/README.md

1. Added a `Feature request` issue template.
2. Refactored the `Bug report` issue template.
3. Added an issue config file with entries for the common types of issues .NET Docker users encounter.
4. Simplified the `Feedback` section of the readmes to contain one `File an issue` link which takes users to the new issue selection page of this repo.
This is a mirror of the changes made for the .NET Core Docker repo in https://github.com/dotnet/dotnet-docker/pull/2313
[skip ci]

Enhance issue templates and issue choices

---

.gitattributes

Fixes https://github.com/microsoft/dotnet-framework-docker/issues/623

Add .gitattributes file to normalize line endings

---

README.aspnet.md
README.runtime.md
README.sdk.md
manifest.json

Undocument the 4.8-3.5 tags

---

eng/common/templates/variables/common-paths.yml
eng/pipelines/variables/common.yml

Target correct path when publishing test results

---

samples/aspnetapp/Dockerfile
samples/aspnetapp/Dockerfile.windowsservercore-ltsc2016
samples/aspnetmvcapp/Dockerfile
samples/dotnetapp/Dockerfile
samples/dotnetapp/Dockerfile.basic

Add --no-restore option to sample Dockerfiles

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/686

Updates for 12B release

---

tests/Microsoft.DotNet.Framework.Docker.Tests/Microsoft.DotNet.Framework.Docker.Tests.csproj
tests/run-tests.ps1

Upgrade test project to .NET 5

---

eng/update-dependencies/DependencyUpdater.cs
eng/update-dependencies/Microsoft.DotNet.Framework.UpdateDependencies.csproj

Upgrade update-dependencies to .NET 5

---

src/sdk/3.5/windowsservercore-1909/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-1909/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

Trigger dotnet 1st-run experience in SDK

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/lcu-info.json
manifest.json
src/runtime/3.5/windowsservercore-1909/Dockerfile
src/runtime/4.8/windowsservercore-1909/Dockerfile

Servicing updates for Windows Server, version 1909

---

eng/dockerfile-templates/aspnet/Dockerfile
eng/dockerfile-templates/aspnet/Dockerfile.3.5.pre20H2
eng/dockerfile-templates/aspnet/Dockerfile.pre20H2
eng/dockerfile-templates/wcf/Dockerfile
manifest.json
src/aspnet/4.6.2/windowsservercore-ltsc2016/Dockerfile
src/aspnet/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/aspnet/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/aspnet/4.7/windowsservercore-ltsc2016/Dockerfile
src/aspnet/4.8/windowsservercore-1909/Dockerfile
src/aspnet/4.8/windowsservercore-2004/Dockerfile
src/aspnet/4.8/windowsservercore-ltsc2016/Dockerfile
src/aspnet/4.8/windowsservercore-ltsc2019/Dockerfile

Add aspnet Dockerfile templates

---

eng/pipelines/dotnet-framework-pr-no-cache.yml
eng/pipelines/dotnet-framework-pr.yml

Add main branch to list of pipeline trigger branches

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/common/templates/jobs/generate-matrix.yml
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-1909/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-1909/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/741

Servicing updates for 3B release

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/754

Updates for 4B servicing

---

README.sdk.md
manifest.json
manifest.versions.json
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/770

Update sdk to use VS 16.10 tools

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
eng/dockerfile-templates/runtime/Dockerfile
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/777

Updates for 6B servicing

---

eng/dockerfile-templates/runtime/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/777

Fix syntax issue in 4.7.2 for 2019

---

.github/ISSUE_TEMPLATE/releases/new-windows-release.md
.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md
.github/ISSUE_TEMPLATE/releases/vs-tools-release.md

Updates the release issue templates to reflect the current process.  
Fixes https://github.com/microsoft/dotnet-framework-docker/issues/783

Update release issue templates

---

eng/dockerfile-templates/runtime/Dockerfile
src/runtime/4.8/windowsservercore-2004/Dockerfile
src/runtime/4.8/windowsservercore-20H2/Dockerfile

Fixes https://github.com/microsoft/dotnet-framework-docker/issues/782

Remove redundant patch installation for 4.8 on 2004 and 20H2

---

README.aspnet.md
README.sdk.md
README.wcf.md
eng/pipelines/dotnet-framework.yml
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/796

Updates for 7B servicing

---

eng/dockerfile-templates/sdk/Dockerfile
eng/dockerfile-templates/sdk/Dockerfile.ltsc2016
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
tests/Microsoft.DotNet.Framework.Docker.Tests/SdkOnlyImageTests.cs

Related to https://github.com/microsoft/dotnet-framework-docker/issues/799

Prevent generation of ASP.NET Core developer certificate

---

README.sdk.md
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/803 and https://github.com/microsoft/dotnet-framework-docker/issues/804

Updates for 8B servicing

---

eng/common/Install-DotNetSdk.ps1

Related to https://github.com/dotnet/core/issues/6556

Workaround .NET install script issue

---

eng/dockerfile-templates/sdk/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile

Consolidate ENV instructions in sdk Dockerfiles

---

README.aspnet.md
README.runtime.md
README.sdk.md
README.wcf.md
manifest.json
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.1/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7.2/windowsservercore-ltsc2016/Dockerfile
src/runtime/4.7/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-2004/Dockerfile
src/sdk/3.5/windowsservercore-20H2/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2016/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2019/Dockerfile
src/sdk/3.5/windowsservercore-ltsc2022/Dockerfile
src/sdk/4.8/windowsservercore-2004/Dockerfile
src/sdk/4.8/windowsservercore-20H2/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2016/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile
src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile

Related to https://github.com/microsoft/dotnet-framework-docker/issues/818

Updates for Sept servicing

---

.mcr/portal/README.aspnet.portal.md
.mcr/portal/README.runtime.portal.md
.mcr/portal/README.samples.portal.md
.mcr/portal/README.sdk.portal.md
.mcr/portal/README.wcf.portal.md
README.aspnet.md
README.md
README.runtime.md
README.samples.md
README.sdk.md
README.wcf.md
eng/readme-templates/FeaturedTags.md
eng/readme-templates/RelatedRepos.md
eng/readme-templates/Use.md

Updates the header names to align with the [names specified for the MAR portal](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/containers-bburns/microsoft-container-registry/microsoft-artifact-registry-also-known-as-microsoft-container-registry-docs/onboardingdocs/documentationstandards).
Also adds WS 2022 for .NET Fx 3.5 to the version compatibility table.

Readme updates

---

eng/common/templates/jobs/build-images.yml

Workaround for https://github.com/dotnet/docker-tools/issues/1152

Pin to specific version of ManifestGeneratorTask

---

.mcr/portal/README.aspnet.portal.md
.mcr/portal/README.runtime.portal.md
.mcr/portal/README.samples.portal.md
.mcr/portal/README.sdk.portal.md
.mcr/portal/README.wcf.portal.md
eng/readme-templates/Url.md

Fix related repositories MCR URLs

---

eng/pipelines/update-readmes.yml
eng/pipelines/variables/common.yml

Related to https://github.com/dotnet/dotnet-docker-internal/issues/4475
[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2405818&view=results) (Microsoft internal link)

Convert the update-readmes pipeline to use 1ES templates

---

eng/common/templates/jobs/build-images.yml
manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile
src/runtime/4.8.1/windowsservercore-ltsc2022/Dockerfile

Related: https://github.com/dotnet/docker-tools/pull/1283

Update KBs for Server 2022 and use newer version of SBOM Manifest Generator Task

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/new-windows-release.md
.github/workflows/lint-code-base.yml

Related to #https://github.com/dotnet/dotnet-docker/issues/5316
This was an oversight on my part with https://github.com/microsoft/dotnet-framework-docker/pull/1155. I included the necessary markdown syntax corrections.

Update linter to validate all code

---

eng/pipelines/variables/common.yml

Related to https://github.com/dotnet/docker-tools/issues/1201

Enable EOL annotations in pipeline

---

manifest.versions.json
src/runtime/3.5/windowsservercore-ltsc2019/Dockerfile
src/runtime/3.5/windowsservercore-ltsc2022/Dockerfile

Update KBs for Server 2019 and 2022

---

eng/common/templates/variables/dotnet/common.yml

Updates the variable names to target the new Azure subscription.

Update variable group names to target new subscription
